## numerical operations on `numpy` arrays


### Section contents

* Elementwise operations
* Basic reductions
* Sorting data
* Summary


## Elementwise operations


### Basic operations


With scalars:

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [2]:
2**a

array([ 2,  4,  8, 16])

## Elementwise operations (2)

All arithmetic operates elementwise:

In [3]:
b = np.ones(4) + 1 # b = array([2.,2.,2.,2.])
a - b

array([-1.,  0.,  1.,  2.])

In [4]:
a * b

array([ 2.,  4.,  6.,  8.])

In [5]:
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

## Elementwise operations (3)
These operations are of course much faster than if you did them in pure
python:


In [6]:
a = np.arange(10000)
t1 = %timeit -o [a + 1]  

The slowest run took 15.79 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 5.95 µs per loop


In [7]:
l = range(10000)
t2 = %timeit -o [i+1 for i in l] 

1000 loops, best of 3: 728 µs per loop


In [8]:
print("Numpy speedUP:", t2.best/t1.best)

Numpy speedUP: 122.3680197034759


## Elementwise operations (4)

**Warning**: *array multiplication is not matrix multiplication:*

In [9]:
c = np.ones((3, 3))
c * c                   # NOT matrix multiplication!

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

**Matrix multiplication:**


In [10]:
c.dot(c)

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

## Hands-on #1: elementwise operations

* Try simple arithmetic elementwise operations.

* Time them against their pure python counterparts using `%timeit`.

* Try using `dot`.

* Generate:

    * `[2**0, 2**1, 2**2, 2**3, 2**4]`

    * `a_j = 2^(3*j) - j`


## Other elementwise operations
Comparisons:

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True], dtype=bool)

In [12]:
a > b

array([False, False,  True, False], dtype=bool)

## Other elementwise operations (2)
Logical operations:

In [13]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)

array([ True,  True,  True, False], dtype=bool)

In [14]:
np.logical_and(a, b)

array([ True, False, False, False], dtype=bool)

## Other elementwise operations (3)
Transcendental functions:


In [15]:
a = np.linspace(1,10,10)
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [16]:
np.log(a)

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791,
        1.79175947,  1.94591015,  2.07944154,  2.19722458,  2.30258509])

In [17]:
np.exp(a)

array([  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
         5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
         1.09663316e+03,   2.98095799e+03,   8.10308393e+03,
         2.20264658e+04])

## Transposition:

In [18]:
a = np.triu(np.ones((3, 3)), 1)   # see help(np.triu)
a

array([[ 0.,  1.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [19]:
a.T

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  1.,  0.]])

## Array-wise comparisons


In [20]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
np.array_equal(a, b)

False

In [21]:
np.array_equal(a, c)

True

## Hands-on #2: Exercise other operations

* Look at the help for `np.allclose`. When might this be useful?

* Look at the help for `np.triu` and `np.tril`.

* Is the transpose a view or a copy?


## Basic reductions
Computing sums:

In [22]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [23]:
x.sum()

10

### Sum by rows and by columns

![A](images/reductions.png)

In [24]:
x = np.array([[1, 1], [2, 2]])

In [25]:
x.sum(axis=0)   # columns (first dimension)

array([3, 3])

In [26]:
x.sum(axis=1)   # rows (second dimension)

array([2, 4])

### Sum by rows and by columns (2)

An alternative syntax:

![A](images/reductions.png)

In [27]:
x[:, 0].sum(), x[:, 1].sum()

(3, 3)

In [28]:
x[0, :].sum(), x[1, :].sum()

(2, 4)

### Sum by rows and by columns (3)
Same idea in higher dimensions:

In [29]:
x = np.random.rand(2, 2, 2)
x.sum(axis=2)[0, 1]     

0.82504599113009258

In [30]:
x[0, 1, :].sum()     

0.82504599113009258

### Other reduction operations
--- works the same way (and take `axis=`)

## Extrema


In [31]:
x = np.array([1, 3, 2])
x.min()

1

In [32]:
x.max()

3

In [33]:
x.argmin()  # index of minimum

0

In [34]:
x.argmax()  # index of maximum

1

## Logical operations:


In [35]:
np.all([True, True, False])

False

In [36]:
np.any([True, True, False])

True

Can be used for array comparisons:


In [37]:
a = np.zeros((100, 100))
np.any(a != 0)

False

In [38]:
np.all(a == a)

True

## Array comparisons: another example

In [39]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

... and many more (best to learn as you go).


## Hands-on #3: Reductions

* Given there is a `sum`, what other function might you expect to see?

* What is the difference between `sum` and `cumsum`?


## Sorting data

Sorting along an axis:


In [40]:
a = np.array([[4, 3, 5], [1, 2, 1]])
a


array([[4, 3, 5],
       [1, 2, 1]])

In [41]:
# Sort inplace
a.sort(axis=1)
a

array([[3, 4, 5],
       [1, 1, 2]])

#### Note: sorts each row separately!


## Sorting the indexes (with fancy indexing):


In [42]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [43]:
# Apply sorted indexes
a[j]
# Equal to a.sort()

array([1, 2, 3, 4])

In [44]:
a.sort()
a

array([1, 2, 3, 4])

## Hands-on #5: Sorting

* Try both in-place and out-of-place sorting.

* Try creating arrays with different dtypes and sorting them.

* Look at `np.random.shuffle` for a way to create sortable input quicker.


## Summary 

* Know how to create arrays : `array`, `arange`, `ones`, `zeros`.

* Know the shape of the array with `array.shape`, then use slicing to obtain different views of the array: `array[::2]`, etc. 
* Obtain a subset of the elements of an array and/or modify their values with masks
* Know miscellaneous operations element-wise on arrays
* Know miscellaneous reduction operations on array

**Beware**: no need to retain everything, but have the reflex to search in the documentation (online docs, `help()`, `lookfor()`)!!


# End of chapter

In [45]:
%reload_ext version_information
%version_information numpy, matplotlib

Software versions
Python 3.4.4 64bit [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
IPython 4.0.3
OS Linux 3.13.0 46 generic x86_64 with debian 8.4
numpy 1.10.2
matplotlib 1.4.3
Thu Jun 16 15:14:13 2016 UTC

You can go to [next chapter](03-scipy.ipynb) now.